sudo: false
language: node_js
node_js: 6
install: yarn
branches:
  except:
    - /^v\d/
after_success:
- yarn run semantic-release
before_deploy: yarn run predeploy
deploy:
  local_dir: vr/build
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
