sudo: false
language: node_js
node_js: 6
install: yarn
branches:
  except:
    - /^v\d/
after_success:
- yarn run semantic-release
deploy:
  provider: script
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master
